version: '3'
services:

  consul:
    image: consul:1.15.3
    ports:
      - "${ZAHORI_CONSUL_PORT}:8500"
    network_mode: bridge

  database:
    image: postgres:12.15-alpine
    restart: always
    ports:
      - "${ZAHORI_DB_PORT}:5432"
    network_mode: bridge
    environment:
     - POSTGRES_DB=${ZAHORI_DB_NAME}
     - POSTGRES_USER=${ZAHORI_DB_ADMIN_USER}
     - POSTGRES_PASSWORD=${ZAHORI_DB_ADMIN_PASS}
    volumes:
#     - ./database/postgres-data:/var/lib/postgresql/data
     - zahori-database:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:8.5.13-alpine
    command: -locations=filesystem:/flyway/sql -url=jdbc:postgresql://${ZAHORI_DB_HOST}:${ZAHORI_DB_PORT}/${ZAHORI_DB_NAME} -user=${ZAHORI_DB_ADMIN_USER} -password=${ZAHORI_DB_ADMIN_PASS} -placeholders.zahori_db_user=${ZAHORI_DB_USER} -placeholders.zahori_db_pass=${ZAHORI_DB_PASS} -baselineOnMigrate="false" -connectRetries=60 migrate
    network_mode: bridge
    links:
      - database
    volumes:
      - ./database/sql_versions:/flyway/sql
    depends_on:
      - database

  zahori-server:
    image: zahoriaut/zahori-server:0.1.17
    ports:
      - "${ZAHORI_SERVER_PORT}:${ZAHORI_SERVER_PORT}"
    network_mode: bridge
    links:
      - database
      - consul
      - selenoid-ui
    environment:
     - ZAHORI_SERVER_PORT=${ZAHORI_SERVER_PORT}
     - ZAHORI_DB_HOST=${ZAHORI_DB_HOST}
     - ZAHORI_DB_PORT=${ZAHORI_DB_PORT}
     - ZAHORI_DB_NAME=${ZAHORI_DB_NAME}
     - ZAHORI_DB_SCHEMA=${ZAHORI_DB_SCHEMA}
     - ZAHORI_DB_USER=${ZAHORI_DB_USER}
     - ZAHORI_DB_PASS=${ZAHORI_DB_PASS}
     - ZAHORI_CONSUL_HOST=${ZAHORI_CONSUL_HOST}
     - ZAHORI_CONSUL_PORT=${ZAHORI_CONSUL_PORT}
     - ZAHORI_SELENOID_UI_INTERNAL_HOST=${ZAHORI_SELENOID_UI_INTERNAL_HOST}
     - ZAHORI_SELENOID_UI_INTERNAL_PORT=${ZAHORI_SELENOID_UI_INTERNAL_PORT}
     - ZAHORI_SELENOID_UI_EXTERNAL_HOST=${ZAHORI_SELENOID_UI_EXTERNAL_HOST}
     - ZAHORI_SELENOID_UI_EXTERNAL_PORT=${ZAHORI_SELENOID_UI_EXTERNAL_PORT}
    volumes:
     - ./evidences:/usr/app/evidences
     - ./logs:/usr/app/logs
     - ./timezone:/etc/timezone:ro
    depends_on:
     - flyway
     - consul
     - selenoid-ui

  selenoid:
    image: "aerokube/selenoid:1.10.12"
    network_mode: bridge
    ports:
      - "${ZAHORI_SELENOID_PORT}:4444"
    volumes:
      - "./selenoid/config:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./selenoid/config/video:/opt/selenoid/video"
      - "./selenoid/config/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=selenoid/config/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-limit", "5"]

  selenoid-ui:
    image: "aerokube/selenoid-ui:1.10.10"
    ports:
      - "${ZAHORI_SELENOID_UI_INTERNAL_PORT}:8080"
    command: ["--selenoid-uri", "http://selenoid:${ZAHORI_SELENOID_PORT}", "--allowed-origin", "*"]
    depends_on:
     - selenoid
    network_mode: bridge
    links:
      - selenoid

  zahori-scheduler:
    image: zahoriaut/zahori-scheduler:1.0.0
    network_mode: bridge
    links:
      - zahori-server
      - consul
    environment:
     - ZAHORI_CONSUL_HOST=${ZAHORI_CONSUL_HOST}
     - ZAHORI_CONSUL_PORT=${ZAHORI_CONSUL_PORT}
    depends_on:
     - zahori-server
     - consul
    volumes:
     - ./timezone:/etc/timezone:ro

#  zahori-process:
#    image: zahoriaut/zahori-process:0.1.12
#    network_mode: bridge
#    links:
#      - zahori-server
#      - consul
#      - selenoid
#    environment:
#     - ZAHORI_SERVER_HOST=http://zahori-server:9090/zahori
#     - ZAHORI_SELENOID_HOST=${ZAHORI_SELENOID_HOST}
#     - ZAHORI_CONSUL_HOST=${ZAHORI_CONSUL_HOST}
#     - ZAHORI_CONSUL_PORT=${ZAHORI_CONSUL_PORT}
#    depends_on:
#     - zahori-server
#     - consul
#    volumes:
#     - ./timezone:/etc/timezone:ro

volumes:
  zahori-database:
    external: true
